### ISSUE TITLE
显示不出来

### ISSUE THREAD

**Issue by zhangfurun** [lvjiaxuan/vue-number-roll#1]
您好,我执行了 npm i vue-number-roll, 然后贴上了代码
<template>
	<number-roll ref="number-roll" endNum="123" roll-height="120px"/>
</template>

但是并没有显示出来

**Comment by zhangfurun** [comment]
希望可以联系到你.
方便的话 提供一个联系方式

**Comment by lvjiaxuan** [comment]
尴尬了
