### ISSUE TITLE
vue3 引入报错

### ISSUE THREAD

**Issue by IDisSoEasy** [lvjiaxuan/vue-number-roll#18]
import NumberRoll from "vue3-number-roll"

vite + vue3 

[vite] Internal server error: Failed to resolve entry for package "vue3-number-roll". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "vue3-number-roll". The package may have incorrect main/module/exports specified in its package.json.

老哥，你这个demo能再详细点吗

**Comment by lvjiaxuan** [comment]
试试最新的，详看 readme
